skip install check

diff --git a/.chezmoiscripts/run_onchange_00_setup.sh.tmpl b/.chezmoiscripts/run_onchange_00_setup.sh.tmpl
--- a/.chezmoiscripts/run_onchange_00_setup.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_00_setup.sh.tmpl
@@ -12,12 +12,12 @@ function install() {
         "$@"
 
         # check the exit code of the previous command
-        if [ $? -eq 0 ]; then
-            echo "$cmd is installed"
-        else
-            echo "installing $cmd failed"
-            exit 1
-        fi
+        # if [ $? -eq 0 ]; then
+        #     echo "$cmd is installed"
+        # else
+        #     echo "installing $cmd failed"
+        #     exit 1
+        # fi
     fi
 }
 
